language: node_js
services:
- mongodb
- redis-server
node_js:
- '0.10'
before_script: npm install --dev
script: npm test
env:
  global:
  - PROVIDER_URL="http://localhost:8000"
  - ANYFETCH_API_ID="fake"
  - ANYFETCH_API_SECRET="fake"
  - secure: A+EqGWgcgTQPi8WBwWvJiJEHAEmCESoGwqo1f9uLjooL2BHHVJEf9AnfRvvK1OSqri72IcN1tYrIfk6mK1NvH80Bowd4gmZY3hlDjdJCR3gMLYQbClGRhgUjZSOrezluT6jfxrykzrD7D6CWMufrl3mi0WkAx7okx+z6NYTIO7Y=
  - secure: eqXo6FZEKXZ6gShvHrqFel1xdBIBCpALubgk9R8sOZ6rj/n9azR7JT8Vr8SESoDcEVVQLZz812JUukR7t1biLBpRuYYhVrF2R9r4fWYPnFL/bJyL048nnTZWWFne3PGr3r2eaUKdP4gCddXP/GZkI9Odk/GdZ4WeSf1vKzxQPAk=
  - secure: di3x5j9hdQTi5ak7aqpoumTTaZJoRR5C77YYpX6RiLSMDMg5TqjTtUN4bwoIqEw2e7UCn0VabSpcAGyj+v1zez5YWC2eHWSFdvp7Oz2FDiT6Uqb9yqGUwYXBiShbZeTfZFk1xpFObf+PseYevVr4+LrnC5i/uQ0Exe0E/7kl20A=
  - secure: OrdM+a427B7tWMWk5HU4+xlfcP/kX3a+XI3nTkMFeqso+cO1cIZT+/LqC2cM2ioOcyQq4su3SsfjsnqE4NrHJAmtmRAk2MVMKZRvnQmgcsyG7n8UkV60jaUxogk/5XsAn7reUmYqodt839vzTaoPX5Lgilzif0f+Nu+QvMAF2xA=
